name: Continous Integration

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10]
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up all python versions
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run Tests
        run: python -m unittest discover tests
